spring:
  datasource:
    url: jdbc:postgresql://datalogging.chc40a682r3a.us-east-1.rds.amazonaws.com:5432/postgres?sslmode=require
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # or validate for production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  datasource.hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 5000